Traceback (most recent call last):
  File "/mnt/c/Users/dell/Desktop/personal/github_repository/mailsender/python-bulk-mail-master/mail.py", line 21, in <module>
    server.login(sender_email, password)
  File "/usr/lib/python3.9/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/lib/python3.9/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.9/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: UGFzc3dvcmQ6')
